### ISSUE TITLE
The DBUnit "Table Type" property is not supported

### ISSUE THREAD

**Issue by mats24** [database-rider/database-rider#235]
I need to change the DBUnit table type from the default {"TABLE"} to {"TABLE", "VIEW"}, as the database "table" I'm manipulating is actually an Oracle view: http://dbunit.sourceforge.net/properties.html#tabletype

However, the database-rider DBUnit annotation does not include a "tableType" attribute.
Is this going to be added in a future release? Or is there some other way of configuring the missing DBUnit properties?

Environment: Spring Boot, JUnit 5, DBUnit, Database Rider.

**Comment by rmpestano** [comment]
Hi @mats24, you can add dbunit properties in [global config file](https://github.com/database-rider/database-rider#332-dbunit-configuration) (`src/test/resources/dbunit.yml`), for example:

```
cacheConnection: false
cacheTableNames: false
leakHunter: true
raiseExceptionOnCleanUp: true
expectedDbType: HSQLDB
properties:
  tableType: {"TABLE", "VIEW"}
  batchedStatements:  true
  caseSensitiveTableNames: false
  qualifiedTableNames: true
  schema: public
  batchSize: 200
  fetchSize: 200
  allowEmptyFields: true
  escapePattern: "[?]"
  datatypeFactory: !!com.github.database.rider.core.configuration.DBUnitConfigTest$MockDataTypeFactory {}
  replacers: [!!com.github.database.rider.core.replacers.CustomReplacer {}]
```
