### ISSUE TITLE
Feature request: entity-based replacers/stereotypes in `yaml`-based datasets

### ISSUE THREAD

**Issue by coiouhkc** [database-rider/database-rider#362]
Scenario: imagine a database where each entity has some mandatory standard additional fields, e.g. `version` for optimistic locking, `changedBy` + `changedAt` for auditing purposes or certain data protection level fields.

It would be nice not have to specify those fields manually in `@DataSet` for each entity, but instead have a possibility to specify a 'replacer' (for lack of the better word and to align with current terminology) / stereotype to be able to generate those fields automatically for each entity listed in the `*.yml` dataset.

Since it should be compatible with YAML, smth. like 
```
table1:
  - replacers:
    - replacer1Name: "[replacer1Config]"
    - replacer2Name: "[replacer2Config]"
  - entity1
  - entity2
```
