### ISSUE TITLE
Feature suggestion: value injection/derivation/substitution in `*.yaml`-based `@ExpectedDataSet`s

### ISSUE THREAD

**Issue by coiouhkc** [database-rider/database-rider#363]
Scenario: testing linked entities in YAML-based `@ExpectedDataSet`
Idea:
```
table1:
  - id: $$x$$
     name: "name2"
  - id: $$y$$
     name: "name1"
table2:
  - table1_id: $$x$$
  - table1_id: $$y$$
```
Workaround: right now it could be circumvented by using `orderBy` in `@ExpectedDataSet`, but the foreign key references are not being tested.
