### ISSUE TITLE
dbunit schema from application.properties.yml

### ISSUE THREAD

**Issue by vladbogun1** [database-rider/database-rider#416]
I have a problem with defining which schema to load, so once dbunit try to get list of tables, he gets the first schema in my db and list of tables from it, which is wrong.
for example if i wanna to use such db:

```
db:
    WRONG_SCHEMA:
        - table1name
        - table2name
    SCHEMA_THAT_I_ACTUALLY_NEED_TO_TEST:
        - table10name
        - table20name
```
so if i have in application.properties  `spring.datasource.url` defined as 
`jdbc:mariadb://${server-url}/${schema-name}?connectionCollation=utf8mb4_unicode_ci&serverTimezone=UTC`
it is gonna connect to the right DB, but `schema `would be `null `and it will take the first public schema in db (WRONG_SCHEMA), which is wrong.
I cant define schema in code as `@DBUnit(url = "SCHEMA_NAME")` because in dockers or anywhere else schema name might be changed. 

**So how can i load schema name in DBUnit configuration from application.yml file?**
