### ISSUE TITLE
Read DBUnit configuration from Spring Boot Properties

### ISSUE THREAD

**Issue by netmikey** [database-rider/database-rider#490]
It seems that #483 does not cover the case where DBRider is used on a `@SpringBootTest` and should use the Spring Properties from that test's Spring context for its configuration. I'm not sure but I don't think these Spring Context Properties are made into System Properties (they're not environment properties obviously, since they can be read in a lot of ways by Spring). I think DBRider would have to rely on Spring's EL (or some other Spring API) to resolve those properties against the running test Sping Context.

E.g.:
**SomeTest.java**
```java
@SpringBootTest
@DBRider
@DataSet("datasets/some-dataset.xml")
public class SomeTest {
    ...
}
```

**dbunit.yml**
```yml
caseInsensitiveStrategy: !!com.github.database.rider.core.api.configuration.Orthography 'LOWERCASE'
columnSensing: true
properties:
  batchedStatements:  true
  schema: ${spring.datasource.username}
```

With DBRider v1.34.0, I get the error:
```
...
Caused by: org.dbunit.dataset.NoSuchTableException: The table 'sometable' does not exist in schema '${spring.datasource.username}'
	at app//org.dbunit.database.search.AbstractMetaDataBasedSearchCallback.getNodes(AbstractMetaDataBasedSearchCallback.java:186)
```
