### ISSUE TITLE
Feature Request: Support YAML overrides

### ISSUE THREAD

**Issue by inhaledesign** [database-rider/database-rider#605]
I'm using Database-Rider for running unit tests. I do lot of manually editing dataset files to create test data. This often involves copying and pasting entries, then tweaking a few things about the copies that I want to test.

It would be nice if we could take advantage of YAML's [override feature](https://www.linode.com/docs/guides/yaml-anchors-aliases-overrides-extensions/) to reduce some typing and increase clarity. The current YAML format used be DB rider does not allow for this, as each table contains a List and adding in overrides turns it into a Map.

What I would like to be able to do would be something like this:

```YAML
BASE_ACCOUNT: &BASE_ACCOUNT
  KEY: '1'
  LAST_DATE: '2023-12-01'
  ACCOUNT_NUMBER: '0000000001'
  PERSON_KEY: '1'
  OPEN_DATE: '1987-10-01'
  TYPE_KEY: '104'
  OPTION_A: 'M'
  OPTION_B: 'E'
  OPTION_C: 'N'
  CYCLE_OPTION: '-'
  RELATIONSHIP_KEY: '2'
  ELIGIBILITY_KEY: '127'
  ACCESS_RESTRICTION: U
  ROW_CHANGE_TIMESTAMP: '2023-12-01 10:44:15.505817'
 
DATASET:
  ACCOUNT:
    - KEY: '2'
      ACCOUNT_NUMBER: '0000000002'
      PERSON_KEY: '2'
      <<: *BASE_ACCOUNT
    - KEY: '3'
      ACCOUNT_NUMBER: '0000000003'
      OPTION_A: 'H'
      <<: *BASE_ACCOUNT
```

Note: Possibly related to #362

**Comment by coiouhkc** [comment]
Interesting idea.
Have you checked, whether SnakeYaml supports it in-place OOB or whether `YamlDataSet` would have to infer the overrides in Java code itself?

**Comment by coiouhkc** [comment]
Btw., I tried (based on https://stackoverflow.com/questions/4948933/is-there-a-way-to-alias-anchor-an-array-in-yaml) it out and it seems to work:
```yaml
ACCOUNT:
    - &BASE_ACCOUNT
      KEY: '1'
      LAST_DATE: '2023-12-01'
      ACCOUNT_NUMBER: '0000000001'
      PERSON_KEY: '1'
      OPEN_DATE: '1987-10-01'
      TYPE_KEY: '104'
      OPTION_A: 'M'
      OPTION_B: 'E'
      OPTION_C: 'N'
      CYCLE_OPTION: '-'
      RELATIONSHIP_KEY: '2'
      ELIGIBILITY_KEY: '127'
      ACCESS_RESTRICTION: U
      ROW_CHANGE_TIMESTAMP: '2023-12-01 10:44:15.505817'
    - KEY: '2'
      ACCOUNT_NUMBER: '0000000002'
      PERSON_KEY: '2'
      <<: *BASE_ACCOUNT
    - KEY: '3'
      ACCOUNT_NUMBER: '0000000003'
      OPTION_A: 'H'
      <<: *BASE_ACCOUNT
```
