### ISSUE TITLE
Unordered @ExpectedDataSet

### ISSUE THREAD

**Issue by TopalSergey** [database-rider/database-rider#76]
Hi,
Possible this issue related only to special cases, but it looks like bug.
The issue is that dataset from @ExpectedDataSet is not sorted before comparing with actual dataset, but actual (org.dbunit.database.DatabaseDataSet) is sorted by primary keys.
And if your expected dataset is not ordered by pk, your test will fail.
Here are example:

>
    @Test
    @DataSet(value = "yml/expectedUsers.yml")
    @ExpectedDataSet(value = "yml/expectedUsers.yml")
    public void testUnorderedDataset() {
    }

where expectedUsers.yml:
>
    USER:
      - ID: 2
        NAME: "expected user2"
      - ID: 1
        NAME: "expected user1"

**Comment by rmpestano** [comment]
Hi, this is related to #71?

**Comment by TopalSergey** [comment]
I don't know, I did not understand what he mean

**Comment by rmpestano** [comment]
I think my comment applies here, a failing test would be nice, a PR would be great!

**Comment by rmpestano** [comment]
maybe an aditional property to specify the order @ExpectedDataset(orderCol="ID") where we would order the expected dataset only if `orderCol` is present. WDYT?

**Comment by TopalSergey** [comment]
it will be not possible to specify different orderCol for different tables in one dataset (as with ignoreCol, if specified, it will be ignored in all tables in dataset).
but i think this is ok for most cases and existing tests will not be affected.

**Comment by rmpestano** [comment]
or maybe an `ignoreOrder=true` and we check if each row of actual dataset is present in expectedDataset. Don't know if its possible but would be great.

**Comment by getarrenspieler** [comment]
What about special property "tag" in dataset? like:

```yml
dbUnit:
   - USER: {orderBy: ID}
   - TWEET: {orderBy: [USER, TEXT]} 
     
USER:
  - ID: 2
    NAME: "expected user2"
  - ID: 1
    NAME: "expected user1"

TWEET:
  - ID: 2
    USER: 1
    TEXT: "expected user1 tweet"
  - ID: 1
    USER: 2
    TEXT: "expected user2 tweet"
```

There can be ignore settings etc.

I don't know what part of job in parsing/comparisionis doing DbUnit itself (mean DbUnit API, not db-rider) and is there technical opportunity to do that. Think it can solve per table configuration propblem in one dataset file (and these settings can be used when reading real database values, not only for dataset file)
